DROP TABLE IF EXISTS "article";

CREATE TABLE "article" (
   "id" SERIAL PRIMARY KEY NOT NULL, 
   "timestamp" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
   "title" STRING(50) DEFAULT NULL, 
   "category" STRING(15) DEFAULT NULL, 
   "abstract" STRING(50) DEFAULT NULL, 
   "articleTags" STRING(15) DEFAULT NULL, 
   "authors" STRING(15) DEFAULT NULL, 
   "language" STRING(2) DEFAULT NULL, 
   "text" STRING(50) DEFAULT NULL, 
   "image" STRING(50) DEFAULT NULL, 
   "video" STRING(50) DEFAULT NULL
);

SHOW COLUMNS from article;