#!/bin/bash

for file in "user"
do
    echo -e "\n\nPopulating table $file \n\n"
    python populate_$file.py

	for file in temp/*
    do
        echo -e "$file"
        cockroach sql --insecure --database=thudb < $file
    done
    rm -rf temp/*
done