DROP TABLE IF EXISTS "user";

CREATE TABLE "user" (
  id SERIAL PRIMARY KEY,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name STRING(50) NOT NULL UNIQUE,
  gender BOOLEAN DEFAULT false, -- true: woman | false: man
  email STRING(80) NOT NULL UNIQUE,
  phone STRING(15) NOT NULL UNIQUE,
  language STRING(2) DEFAULT NULL,
  region STRING(50) DEFAULT NULL,
  dept INT DEFAULT 0,
  grade INT DEFAULT 0,
  role INT DEFAULT 0,
  preferTags STRING(15) DEFAULT NULL,
  obtainedCredits INT DEFAULT 0
);

SHOW COLUMNS from "user";

